// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcsiqhxghfmrbshmodzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjc2lxaHhnaGZtcmJzaG1vZHppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTcwMzAsImV4cCI6MjA2Nzg5MzAzMH0.DvtETHwuYvqoxGjZgQWb68NBrCUSLczHrU1Jpj3HRtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});